### ISSUE TITLE
No possibility to release new versions on npm

### ISSUE THREAD

**Issue by simbo** [simbo/gulp-marked#18]
I took over this repo from @t8g as it lacked maintenance and he obviously didn't want to work on it anymore.

Nevertheless, he refused to transfer the npm package ownership, although i asked for it multiple times.

Therefor i can't release updates (or deprecate it according to #9).

There still seem to be people using this plugin and also improvements waiting to be merged (#17).

I just want to let you know about the situation.

If this is not changing in the near future, i will propably just delete the repo if no one else volunteers to maintain it.

**Comment by t8g** [comment]
In fact you only ask me once and I forgot to proceed.
Sorry, it's now done.

Is this ok for you ?

Le mer. 20 avr. 2016 à 18:25, Simon Lepel <notifications@github.com> a
écrit :

**Comment by flekschas** [comment]
Any updates?
